// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57zH62fPHlELsotDjhtjGyF6CNQg0raU',
    appId: '1:690659016419:web:fee37f81fd1f70d6580fd6',
    messagingSenderId: '690659016419',
    projectId: 'dstcsrichairvitccapp',
    authDomain: 'dstcsrichairvitccapp.firebaseapp.com',
    storageBucket: 'dstcsrichairvitccapp.firebasestorage.app',
    measurementId: 'G-YK2W3Y1M3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0PZblgGwTXtqHaShkE-QL7VQkI42jUc',
    appId: '1:690659016419:android:92884f949ef89308580fd6',
    messagingSenderId: '690659016419',
    projectId: 'dstcsrichairvitccapp',
    storageBucket: 'dstcsrichairvitccapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsPVqSLnvQf-lb1WYRrUN6LA-fAuXVbKE',
    appId: '1:690659016419:ios:06313bbc156203ca580fd6',
    messagingSenderId: '690659016419',
    projectId: 'dstcsrichairvitccapp',
    storageBucket: 'dstcsrichairvitccapp.firebasestorage.app',
    iosBundleId: 'com.example.dstcsriChairVitccApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsPVqSLnvQf-lb1WYRrUN6LA-fAuXVbKE',
    appId: '1:690659016419:ios:06313bbc156203ca580fd6',
    messagingSenderId: '690659016419',
    projectId: 'dstcsrichairvitccapp',
    storageBucket: 'dstcsrichairvitccapp.firebasestorage.app',
    iosBundleId: 'com.example.dstcsriChairVitccApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57zH62fPHlELsotDjhtjGyF6CNQg0raU',
    appId: '1:690659016419:web:dbf88683ea5b6057580fd6',
    messagingSenderId: '690659016419',
    projectId: 'dstcsrichairvitccapp',
    authDomain: 'dstcsrichairvitccapp.firebaseapp.com',
    storageBucket: 'dstcsrichairvitccapp.firebasestorage.app',
    measurementId: 'G-9C8MT0Y28B',
  );
}
